spring:
  application:
    name: spring-security
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.223.129/liuxy?useUnicode=true&characterEncoding=utf8&useSSL=true
    username: root
    password: jnsl123
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    mode: HTML
    cache: false

server:
  port: 8888
logging:
  level:
    root: WARN
    org.springframework.web: INFO
    org.hibernate : INFO
    org.springframework.security: INFO